export const studentInfo = [
  {
    "student_id": "S4293",
    "name": "David Lee",
    "gender": "Male",
    "course": "Electrical and Electronics Engineering (EEE)",
    "credits": 4,
    "grade": "A",
    "country": "India",
    "moreDetails": {
      "email": "student4293@university.com",
      "phone": "+91-1234567890",
    },
  },
  {
    "student_id": "S1248",
    "name": "Sophia Lewis",
    "gender": "Female",
    "course": "Computer Science and Engineering (CSE)",
    "credits": 3,
    "grade": "B+",
    "country": "Japan",
    "moreDetails": {
      "email": "student1248@university.com",
      "phone": "+81-2345678901",
    },
  },
  {
    "student_id": "S8734",
    "name": "Olivia Hall",
    "gender": "Non-binary",
    "course": "Mechanical Engineering (ME)",
    "credits": 5,
    "grade": "B",
    "country": "South Korea",
    "moreDetails": {
      "email": "student8734@university.com",
      "phone": "+82-3456789012",
    },
  },
  {
    "student_id": "S3209",
    "name": "Michael Miller",
    "gender": "Male",
    "course": "Civil Engineering",
    "credits": 4,
    "grade": "C",
    "country": "China",
    "moreDetails": {
      "email": "student3209@university.com",
      "phone": "+86-4567890123",
    },
  },
  {
    "student_id": "S5672",
    "name": "Emily Davis",
    "gender": "Female",
    "course": "Mathematics",
    "credits": 3,
    "grade": "A",
    "country": "Bangladesh",
    "moreDetails": {
      "email": "student5672@university.com",
      "phone": "+880-5678901234",
    },
  },
  {
    "student_id": "S9321",
    "name": "James Allen",
    "gender": "Male",
    "course": "Philosophy",
    "credits": 2,
    "grade": "B+",
    "country": "Nepal",
    "moreDetails": {
      "email": "student9321@university.com",
      "phone": "+977-6789012345",
    },
  },
  {
    "student_id": "S8471",
    "name": "Mia Green",
    "gender": "Female",
    "course": "Biomedical Engineering",
    "credits": 4,
    "grade": "A",
    "country": "Pakistan",
    "moreDetails": {
      "email": "student8471@university.com",
      "phone": "+92-7890123456",
    },
  },
  {
    "student_id": "S1745",
    "name": "Henry Adams",
    "gender": "Male",
    "course": "History",
    "credits": 3,
    "grade": "B",
    "country": "Sri Lanka",
    "moreDetails": {
      "email": "student1745@university.com",
      "phone": "+94-8901234567",
    },
  },
  {
    "student_id": "S5689",
    "name": "Liam Walker",
    "gender": "Non-binary",
    "course": "Chemical Engineering",
    "credits": 5,
    "grade": "C+",
    "country": "Thailand",
    "moreDetails": {
      "email": "student5689@university.com",
      "phone": "+66-9012345678",
    },
  },
  {
    "student_id": "S9253",
    "name": "Chloe Turner",
    "gender": "Female",
    "course": "Biology",
    "credits": 4,
    "grade": "A",
    "country": "Vietnam",
    "moreDetails": {
      "email": "student9253@university.com",
      "phone": "+84-1234567890",
    },
  },
];
