export const faculties = [
  {
    id: 1,
    name: "Dr. Rahman Ali",
    designation: "Professor",
    subject: "Computer Science",
    university: "Ocean Capp University of Bangladesh",
    office_hours: "Mon-Wed 10 AM - 12 PM",
    contact_details: {
      email: "rahman.ali@university.edu",
      phone: "+880123456789",
    },
    profile_photo: "https://unsplash.com/photos/FGDP9zGfhS0",
  },
  {
    id: 2,
    name: "Prof. Kamal Ahmed",
    designation: "Associate Professor",
    subject: "Electrical Engineering",
    university: "Ocean Capp University of Bangladesh",
    office_hours: "Tue-Thu 2 PM - 4 PM",
    contact_details: {
      email: "kamal.ahmed@university.edu",
      phone: "+880987654321",
    },
    profile_photo: "https://unsplash.com/photos/JvA1lp4Hsqc",
  },
  {
    id: 3,
    name: "Dr. Sara Hossain",
    designation: "Assistant Professor",
    subject: "Mechanical Engineering",
    university: "Ocean Capp University of Bangladesh",
    office_hours: "Mon-Wed 1 PM - 3 PM",
    contact_details: {
      email: "sara.hossain@university.edu",
      phone: "+880567891234",
    },
    profile_photo: "https://unsplash.com/photos/IuLgi9PWETU",
  },
  {
    id: 4,
    name: "Prof. Akhtar Uddin",
    designation: "Professor",
    subject: "Mathematics",
    university: "Ocean Capp University of Bangladesh",
    office_hours: "Tue-Thu 10 AM - 12 PM",
    contact_details: {
      email: "akhtar.uddin@university.edu",
      phone: "+880456789123",
    },
    profile_photo: "https://unsplash.com/photos/mEZ3PoFGs_k",
  },
  {
    id: 5,
    name: "Dr. Meherunnisa Parvin",
    designation: "Lecturer",
    subject: "Physics",
    university: "Ocean Capp University of Bangladesh",
    office_hours: "Mon-Fri 9 AM - 11 AM",
    contact_details: {
      email: "meherunnisa.parvin@university.edu",
      phone: "+880678912345",
    },
    profile_photo: "https://unsplash.com/photos/v9FQR4tbIq8",
  },
  {
    id: 6,
    name: "Dr. Abdullah Khan",
    designation: "Professor",
    subject: "Chemistry",
    university: "Ocean Capp University of Bangladesh",
    office_hours: "Mon-Tue 11 AM - 1 PM",
    contact_details: {
      email: "abdullah.khan@university.edu",
      phone: "+880789123456",
    },
    profile_photo: "https://unsplash.com/photos/GwVmNuocSU0",
  },
  {
    id: 7,
    name: "Dr. Nurjahan Begum",
    designation: "Assistant Professor",
    subject: "Biology",
    university: "Ocean Capp University of Bangladesh",
    office_hours: "Wed-Fri 9 AM - 11 AM",
    contact_details: {
      email: "nurjahan.begum@university.edu",
      phone: "+880891234567",
    },
    profile_photo: "https://unsplash.com/photos/YzSZN3qvHeo",
  },
  {
    id: 8,
    name: "Prof. Shahidul Islam",
    designation: "Professor",
    subject: "Civil Engineering",
    university: "Ocean Capp University of Bangladesh",
    office_hours: "Mon-Wed 2 PM - 4 PM",
    contact_details: {
      email: "shahidul.islam@university.edu",
      phone: "+880912345678",
    },
    profile_photo: "https://unsplash.com/photos/44OoIaymGaM",
  },
  {
    id: 9,
    name: "Dr. Farzana Yasmin",
    designation: "Associate Professor",
    subject: "Economics",
    university: "Ocean Capp University of Bangladesh",
    office_hours: "Mon-Tue 10 AM - 12 PM",
    contact_details: {
      email: "farzana.yasmin@university.edu",
      phone: "+880123456780",
    },
    profile_photo: "https://unsplash.com/photos/mEZ3PoFGs_k",
  },
  {
    id: 10,
    name: "Dr. Mahbub Alam",
    designation: "Professor",
    subject: "Psychology",
    university: "Ocean Capp University of Bangladesh",
    office_hours: "Wed-Thu 1 PM - 3 PM",
    contact_details: {
      email: "mahbub.alam@university.edu",
      phone: "+880234567890",
    },
    profile_photo: "https://unsplash.com/photos/yo01Z-9HQAw",
  },
  {
    id: 11,
    name: "Dr. Tasnim Haque",
    designation: "Assistant Professor",
    subject: "Philosophy",
    university: "Ocean Capp University of Bangladesh",
    office_hours: "Mon-Fri 12 PM - 2 PM",
    contact_details: {
      email: "tasnim.haque@university.edu",
      phone: "+880345678901",
    },
    profile_photo: "https://unsplash.com/photos/W6yyfcqKq2s",
  },
  {
    id: 12,
    name: "Prof. Jamal Uddin",
    designation: "Professor",
    subject: "Sociology",
    university: "Ocean Capp University of Bangladesh",
    office_hours: "Tue-Thu 9 AM - 11 AM",
    contact_details: {
      email: "jamal.uddin@university.edu",
      phone: "+880456789012",
    },
    profile_photo: "https://unsplash.com/photos/eOcyhe5-9sQ",
  },
  {
    id: 13,
    name: "Dr. Salma Khatun",
    designation: "Lecturer",
    subject: "History",
    university: "Ocean Capp University of Bangladesh",
    office_hours: "Mon-Wed 11 AM - 1 PM",
    contact_details: {
      email: "salma.khatun@university.edu",
      phone: "+880567890123",
    },
    profile_photo: "https://unsplash.com/photos/vvLtgnCSTmA",
  },
  {
    id: 14,
    name: "Prof. Jahangir Alam",
    designation: "Associate Professor",
    subject: "Political Science",
    university: "Ocean Capp University of Bangladesh",
    office_hours: "Mon-Tue 3 PM - 5 PM",
    contact_details: {
      email: "jahangir.alam@university.edu",
      phone: "+880678901234",
    },
    profile_photo: "https://unsplash.com/photos/l1MCA0VyNrk",
  },
  {
    id: 15,
    name: "Dr. Rasheda Parveen",
    designation: "Professor",
    subject: "Geography",
    university: "Ocean Capp University of Bangladesh",
    office_hours: "Tue-Fri 10 AM - 12 PM",
    contact_details: {
      email: "rasheda.parveen@university.edu",
      phone: "+880789012345",
    },
    profile_photo: "https://unsplash.com/photos/mEZ3PoFGs_k",
  },
  {
    id: 16,
    name: "Dr. Faruk Hossain",
    designation: "Assistant Professor",
    subject: "Business Administration",
    university: "Ocean Capp University of Bangladesh",
    office_hours: "Mon-Wed 10 AM - 12 PM",
    contact_details: {
      email: "faruk.hossain@university.edu",
      phone: "+880890123456",
    },
    profile_photo: "https://unsplash.com/photos/pAWY7xrsLwc",
  },
  {
    id: 17,
    name: "Prof. Nazmul Haque",
    designation: "Professor",
    subject: "Environmental Science",
    university: "Ocean Capp University of Bangladesh",
    office_hours: "Tue-Thu 2 PM - 4 PM",
    contact_details: {
      email: "nazmul.haque@university.edu",
      phone: "+880901234567",
    },
    profile_photo: "https://unsplash.com/photos/mEZ3PoFGs_k",
  },
  {
    id: 18,
    name: "Dr. Arifa Akter",
    designation: "Lecturer",
    subject: "Linguistics",
    university: "Ocean Capp University of Bangladesh",
    office_hours: "Mon-Tue 9 AM - 11 AM",
    contact_details: {
      email: "arifa.akter@university.edu",
      phone: "+880123456790",
    },
    profile_photo: "https://unsplash.com/photos/l68Z6eF2peA",
  },
  {
    id: 19,
    name: "Prof. Abdullah Al Mamun",
    designation: "Professor",
    subject: "Law",
    university: "Ocean Capp University of Bangladesh",
    office_hours: "Wed-Fri 1 PM - 3 PM",
    contact_details: {
      email: "abdullah.mamun@university.edu",
      phone: "+880234567891",
    },
    profile_photo: "https://unsplash.com/photos/zD-Iz4DPQRk",
  },
  {
    id: 20,
    name: "Dr. Tahmina Sultana",
    designation: "Assistant Professor",
    subject: "Anthropology",
    university: "Ocean Capp University of Bangladesh",
    office_hours: "Mon-Fri 9 AM - 11 AM",
    contact_details: {
      email: "tahmina.sultana@university.edu",
      phone: "+880345678912",
    },
    profile_photo: "https://unsplash.com/photos/QXevDflbl8A",
  },
];
